####################################################################################
###  420-2G2 - Programmation orientée objet
###  Travail: Projet Synthèse (Clinique)
###  Nom: Félix Hotte-Tranchemontagne
###  No étudiant: 2134152
###  No Groupe: 002
###  Description du fichier: Code pour l'interface graphique principale
####################################################################################

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfacegraphiqueMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CliniqueMain(object):
    def setupUi(self, CliniqueMain):
        CliniqueMain.setObjectName("CliniqueMain")
        CliniqueMain.resize(443, 344)
        self.centralwidget = QtWidgets.QWidget(CliniqueMain)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_main_patient = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_main_patient.setGeometry(QtCore.QRect(120, 60, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_main_patient.setFont(font)
        self.pushButton_main_patient.setObjectName("pushButton_main_patient")
        self.pushButton_main_rdv = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_main_rdv.setGeometry(QtCore.QRect(120, 110, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_main_rdv.setFont(font)
        self.pushButton_main_rdv.setObjectName("pushButton_main_rdv")
        self.pushButton_main_intervenant = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_main_intervenant.setGeometry(QtCore.QRect(120, 160, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_main_intervenant.setFont(font)
        self.pushButton_main_intervenant.setObjectName("pushButton_main_intervenant")
        self.pushButton_quitter_main = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_quitter_main.setGeometry(QtCore.QRect(120, 210, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_quitter_main.setFont(font)
        self.pushButton_quitter_main.setObjectName("pushButton_quitter_main")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 30, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        CliniqueMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CliniqueMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 443, 21))
        self.menubar.setObjectName("menubar")
        CliniqueMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CliniqueMain)
        self.statusbar.setObjectName("statusbar")
        CliniqueMain.setStatusBar(self.statusbar)

        self.retranslateUi(CliniqueMain)
        QtCore.QMetaObject.connectSlotsByName(CliniqueMain)

    def retranslateUi(self, CliniqueMain):
        _translate = QtCore.QCoreApplication.translate
        CliniqueMain.setWindowTitle(_translate("CliniqueMain", "MainWindow"))
        self.pushButton_main_patient.setText(_translate("CliniqueMain", "Patient"))
        self.pushButton_main_rdv.setText(_translate("CliniqueMain", "Rendez-vous"))
        self.pushButton_main_intervenant.setText(_translate("CliniqueMain", "Intervenant"))
        self.pushButton_quitter_main.setText(_translate("CliniqueMain", "Quitter"))
        self.label.setText(_translate("CliniqueMain", "Bienvenue à la clinique"))
